louisVottero/vtool

- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/curve.py
- python/vtool/maya_lib/space.py
Trying to get Ramen running fast, and was able to make these improvements. 
- Get a unique name simplified in the code, removed from class structure, should speed things up a little
- Get  space.get_axis_vector sped up substantially.
> Improvement: Rig build speed up

- python/vtool/util.py
increment_last_number can be convenient to version up a string, etc.
Adding the padding option makes it more flexible
> Improvement: increment_last_number added a padding length option

- python/vtool/maya_lib/shade.py
- python/vtool/process_manager/ui_options.py
- python/vtool/util_file.py
removed from util_file.fix_slashes()
```
if not directory.find('https://') > -1:
directory = directory.replace('//', '/')
```
> Bug Fix:  Thanks to https://github.com/YKdvd  for pointing out that its not needed to convert // to /

- python/vtool/version.txt
> version 0.5.5.4

- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_util.py
Control Groups now have a built in controlVisiblity and subVisibility 
Control Groups now have a size attribute, that reflects the current size in worldSpace of the control_group
> Improvements: Control group

- python/vtool/data.py
* better handling of non-unique
* if one selection try to find one folder export that matches
* better feedback when weights are unable to import
> Bug Fix: skin weight import fixes

- python/vtool/maya_lib/geo.py
- python/vtool/maya_lib/rigs_util.py
This bug fix also contains a fix to 
create_curve_from_edge_loop to use offset curve instead of poly move.
> Bug Fix: Control.copy_shapes wasn't copying the color properly

- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/space.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
- python/vtool/qt_ui.py
This adds a new button into the structure that helps users to auto orient a hierarchy. 
This configures the orient attributes, allowing for further tweaking after the first pass
> Feature: Auto orient

- python/vtool/maya_lib/space.py
mirror _L_ fix for control cvs and joints
> Improvement: mirror "_L_" pattern on control cvs and joints

- python/vtool/maya_lib/curve.py
- python/vtool/qt_ui.py
When controls build, and Maya is set to z up instead of y up, things still build.
> Improvement: fix for curve z up

- docs/index.rst
> added an index.rst to the documentation

- docs/index.rst
just testing auto doc here https://vetala-auto-rig.readthedocs.io/en/latest/
> removed test

- python/vtool/qt_ui.py
- python/vtool/run_script_manager.py
- python/vtool/script_manager/script_view.py
Script Manager is an old ui that can be used to share code snippets between users.  This fixes some issues with the unused ui.
> Improvement: better Script Manager

- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_util.py
IkAppendageRig stretchy ik was not updating properly with the control_group.size.  This update fixes it.
> Fix: IkAppendageRig was not properly hooked up to control_group.size

- python/vtool/maya_lib/rigs.py
* IkAppendageRig non-unique name fixes.
* layering buffer rigs now gives some more feedback when set_buffer state doesn't match previous rigs.
> Fix: Buffer rig layering fixes.

- python/vtool/data.py
- python/vtool/maya_lib/curve.py
When importing curve data with z up it was aligned wrongly
> Fix: curve solves better with z up

- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/space.py
Added space.orient_x_to_child parent_rotate option 
this helps fix rig.fix_x_axis be more consistent in its joint orientation
> Improvement: space.orient_x_to_child

- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
**Remove on Selected Mesh/Vertices**
This is meant for removing small weights that might seep as the weights gets smoothed,etc
In thise case I give it *_R, and select vertices on the left side to make sure that my right side weights are not affecting left side of the mesh 
**Transfer on Selected Meshes**
This will only work from one joint to one joint, looking to get it working from multiple joints to multipe joints in the future
> Improvement: Remove Weights and Transfer weights from joint to joint in the UI

- python/vtool/data.py
- python/vtool/process_manager/ui_data.py
This fixes skin weight export all to use shortnames where possible.  Causing less issues confusion when importing weights.
> Fix: Skin Weight Export All 

- python/vtool/maya_lib/blendshape.py
- python/vtool/util_file.py
command being passed to subprocess.Popen was not running correctily
changed from rsyn to cp to copy, wasn't using rsync functionality
> Fix: util_file.fast_copy linux

- python/vtool/maya_lib/blendshape.py
- python/vtool/maya_lib/deform.py
transfer blendshapes was having issue with non-unique names
> Fix: blendshape transfer

- python/vtool/qt_ui.py
Fixes:
https://github.com/louisVottero/vtool/issues/110
> Fix: ctrl-s in button script error

- python/vtool/maya_lib/rigs.py
Using FkScaleRig with use hierarchy parenting was not respecting the joint buffer
> Fkix Use hierarchy FkScaleRig fix

- python/vtool/maya_lib/rigs.py
This rig currently gives two levels of control defined by set_control_count and set_sub_control_count
eventually there will be an optional 3rd level
This leverages the ribbon class and has all of the functionality of the ribbons in FkCurveRig
> New: TweaklevelRig

- python/vtool/maya_lib/rigs.py
IkBackLegRig has further improvements that are shown in the vtool_templates quadruped rig
TweakLevelRig has further improvements that are also sown in the vtool_templates quadruped rig
> Fix: IkBackLegRig and TweakLevelRig

- python/vtool/maya_lib/rigs.py
In this iteration aims stay on has the ribbon compresses but maintain a small distance from each other.
This removes a bit of popping that was present before
> Fix: Turning stretch off on ribbons is now more stable

- python/vtool/process_manager/ui_process_manager.py
added splitter automation when switching to Data and Code
> splitter convenience fixes

- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/rigs.py
further fixes and improvements to Quadruped setup
> Fix: Quadruped

- python/vtool/data.py
- python/vtool/process_manager/ui_process_settings.py
> Improvement: Added maya project settings

- python/vtool/process_manager/ui_process_manager.py
Goto to data tab to check versions
> Fix: Save Build Button added in instead of widget

- python/vtool/process_manager/ui_data.py
- python/vtool/process_manager/ui_options.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/qt_ui.py
* Open build added.
* Save and open build more compact.
* Browse and Help moved beside settings button
* Tabs behavior refined
> Improvement: Tweaked tab layou, header/footers

- python/vtool/process_manager/ui_process_manager.py
* Fixes when selecting a project in the settings
* Fixes when deselecting process
> Fix: process update fixes

- python/vtool/maya_lib/core.py
- python/vtool/process_manager/batch.py
- python/vtool/process_manager/batch_deadline.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_settings.py
- python/vtool/render_farm/util_deadline.py
- python/vtool/util_file.py
Added ability to remap paths
Added ability to set where vtool sources from
Fix some pathing issues with batch_deadline
> Improvement: Deadline

- python/vtool/process_manager/ui_code.py
switched "Edit" button to "Drag and Drop" in the Code tab
> changed edit button to drag and drop in the code

- python/vtool/process_manager/ui_process_manager.py
from vtool.process_manager import ui_process_manager
ui_process_manager.signals.update_process_list.emit()
will cause the process_list to refresh
> added signals to force update the ui from custom scripts

- python/vtool/maya_lib/ui.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
seeing if this will fix a long standing bug where the window would lock
> removing auto dock beside hub

- python/vtool/__init__.py
- python/vtool/data.py
- python/vtool/maya_lib/blendshape.py
- python/vtool/maya_lib2/rigs.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/qt_ui.py
- python/vtool/ramen/eval.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/ramen/ui_lib/ui_ramen.py
- python/vtool/ramen/util.py
- python/vtool/unreal_lib/__init__.py
- python/vtool/unreal_lib/util.py
- python/vtool/util_file.py
getting connections to evaluate better
working on unreal integration
working on class structures
> ramen save and eval work as well as some unreal

- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_view.py
before
process.copy_process(process_inst, target_inst)
after
process.copy_process(process_inst, target_directory)
> Fix: duplicate process process.copy_process changed

- python/vtool/maya_lib/ui_core.py
This fixes an issue where importing correctives would error using the import button in the data ui
> Fix: corrective import when using the data button

- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/space.py
initial pass to add inverted scale to hierarchies
> Orient scale chain fix

- python/vtool/maya_lib/core.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/ramen/eval.py
- python/vtool/ramen/rigs.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/ramen/ui_lib/ui_ramen.py
- python/vtool/ramen/util.py
- python/vtool/stylesheet
- python/vtool/unreal_lib/space.py
- python/vtool/unreal_lib/util.py
- python/vtool/util.py
> Ramen work4

- python/vtool/process_manager/ui_data.py
- python/vtool/stylesheet
Sub folders are now hidden from data list
Side sub folder list is now hidden by default. Easy to reveal with the splitter handle
> Improvement: Some tweaks to the data tab

- python/vtool/ramen/rigs.py
- python/vtool/ramen/rigs_maya.py
- python/vtool/ramen/rigs_unreal.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/ramen/util.py
In this pass I'm mostly troubleshooting and cleaning how the graph loads
> Work on ramen graph

- python/vtool/data.py
- python/vtool/maya_lib/api.py
- python/vtool/maya_lib/attr.py
- python/vtool/maya_lib/blendshape.py
- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/corrective.py
- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/fx.py
- python/vtool/maya_lib/geo.py
- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_dev.py
- python/vtool/maya_lib/rigs_util.py
- python/vtool/maya_lib/space.py
- python/vtool/maya_lib/ui_lib/ui_corrective.py
- python/vtool/maya_lib/ui_lib/ui_presets.py
- python/vtool/maya_lib2/space.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_code.py
- python/vtool/process_manager/ui_options.py
- python/vtool/render_farm/util_deadline.py
- python/vtool/util.py
- python/vtool/util_file.py
https://docs.python.org/3/reference/compound_stmts.html#function-definitions
These changes are aimed at avoiding mutability issues that arise with default argument types that are mutable. This can make it very difficult to track down bugs and unexpected phenomena.
> replacement of default mutable arguments with None.

- python/vtool/data.py
- python/vtool/process_manager/ui_settings.py
- python/vtool/qt_ui.py
- python/vtool/script_manager/script_view.py
Some logic reversions, spurred by concerns from the following PRs https://github.com/louisVottero/vtool/pull/298 and https://github.com/louisVottero/vtool/pull/307. Hopefully this should negate any bugs potentially introduced.
> Logic reversion 11 06 2023

- python/vtool/process_manager/batch.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_code.py
- python/vtool/process_manager/ui_data.py
- python/vtool/qt_ui.py
- python/vtool/render_farm/util_deadline.py
- python/vtool/util.py
- python/vtool/util_file.py
- python/vtool/util_math.py
So, the changes:
- Refactor of some of the helper functions for dealing with paths.
- Removal of get python version and replacement with sys.version_info.major
- Cleaning up some getters.
- Conversion of a list to tuples for into to months conversions.
- Minor logic optimization tweaks.
> Util file cleanup 11 07 2023

- python/vtool/data.py
- python/vtool/util_file.py
Alrighty,
This is a big cleanup of various for loops and logic:
- Conversion to higher-order functions where applicable, I.E. map, filter, any, next. (This should speed things up, or at the least make stuff much more legible and the intentions of the programmer clearer.
- Conversion to list comprehensions to increase speed.
- Added docstring stubs for type hint checking in the IDE.
- Removed some unused variables.
- Conversion to using .extend() for list concatenations rather than operator overloading. This makes it clearer what is going on and marginally speeds stuff up.
- Reduced the overall LOC of the data file by a couple percentile.
> Data iterator cleanup 11 29 2023

- python/vtool/data.py
This is a small optimization that supplies the eval function and a method directly to the map function. This shouldn't change anything aside from boosting performance and making the code somewhat more legible. These original lambdas were added by myself in the below pull request but can be removed.
https://github.com/louisVottero/vtool/pull/333
> Lambda cleanup for map

- python/vtool/data.py
- python/vtool/maya_lib/attr.py
- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/corrective.py
- python/vtool/maya_lib/curve.py
- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/geo.py
- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_util.py
- python/vtool/maya_lib/space.py
- python/vtool/maya_lib/ui_lib/ui_corrective.py
- python/vtool/maya_lib2/space.py
- python/vtool/process_manager/ui_code.py
- python/vtool/process_manager/ui_templates.py
- python/vtool/process_manager/ui_view.py
- python/vtool/qt_ui.py
- python/vtool/ramen/rigs_unreal.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/util_file.py
This PR aims to cleanup many of the iterators and increment variables used in loops. One can use the enumerate function instead of cluttering the stack and code with separate variables. This leads to simpler and easier-to-understand code.
https://realpython.com/python-enumerate/
> Enumerate cleanup 12 21 2023

- python/vtool/process_manager/process.py
- python/vtool/qt.py
- python/vtool/qt_ui.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/ramen/ui_lib/ui_ramen.py
- python/vtool/util.py
Separating the graphics out to be able to run the graph without PySide.
> ramen headless batch mode working

- python/vtool/data.py
- python/vtool/houdini_lib/core.py
- python/vtool/process_manager/ui_data.py
- python/vtool/util_file.py
This implements houdini file save/open/import as well as houdini nodes export/import
> Feature: Houdini file and node data 

- python/vtool/process_manager/ui_data.py
Corrective buttons in the data were not loading due to a bug. This is now fixed
> Fix: corrective buttons 

- python/vtool/maya_lib/attr.py
This breaks the curl functionality of FkCurlRig into its own function to easily be used on any fk control chain
> Improvement: Added utility for curl connection

- python/vtool/maya_lib/space.py
small typo crept in with last push
> fixed space typo

- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/unreal_lib/__init__.py
- python/vtool/unreal_lib/core.py
Fixes sources core module of unreal_lib outside of unreal.
> Fix: unreal compatibility

- python/vtool/maya_lib/rigs.py
FkRig use_hierarchy_to_inform_color and use_hierarchy_to_inform_size now work if use_hierarchy_to_inform_parenting is turned off.
TweakLevelRig no longer creates sub controls if rig.set_sub_control_count = 0
> Fix: FkRig, TweakLevelRig

- python/vtool/ramen/ui_lib/ui_nodes.py
This adds the ability to ctrl+d duplicate nodes
> Improvement: Ramen duplicate node

- python/vtool/data.py
- python/vtool/maya_lib/core.py
- python/vtool/process_manager/ui_data.py
This adds thumbnails to the data 
Currently only supported for Maya Ascii and Maya Binary
> Feature: Data thumbnails

- python/vtool/maya_lib/curve.py
Check if self.curve_data_path exists in CurveDataInfo before loading librarires.
> Fix: Better error message CurveDataInfo

- python/vtool/ramen/rigs_unreal.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/unreal_lib/graph.py
* Sub Control tagging by forcing missing connections. 
* Sub control parenting fix as well
> Fix: Ramen Unreal Sub Controls

- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/deform.py
- python/vtool/process_manager/process.py
core.get_characters - namespace check, 
deform.XformTransferAccurate - check for bone existence
> Fix: core.get_characters, deform.XformTransferAccurate

- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/ramen/ui_lib/ui_ramen.py
The ramen graph now versions up on save
> Added: Ramen versioning

- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
Added a button for updating the centroids stored on the boines
> Improvement: Transfer accurate update bones utility

- python/vtool/ramen/rigs_maya.py
* unicode catch for python2
* attribute control get the last parent or sub first parent.
> Fix: Foot roll python2 issue and parenting issue

- python/vtool/ramen/ui_lib/ui_nodes.py
Fixes the style of the color node and removes the title
> Fix: color node

- python/vtool/process_manager/ui_process_manager.py
- python/vtool/ramen/util.py
- python/vtool/unreal_lib/graph.py
* Fix sub control bug
* Fix getting joints from non existent control rig
* Fix window always always on top
> Unreal bug fixes

- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_code.py
- python/vtool/process_manager/ui_data.py
- python/vtool/qt_ui.py
Keep python files and json files that don't live in the manifest here.
> Improvement: Scripts Tab added to Code Tab

- python/vtool/util.py
Fixes issue on MacOS where Maya is missing a command cmds.mayaDpiSetting
> Fix: Mac dpi

- python/vtool/data.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_data.py
When copying data copy the data.json to copy over the settings. 
If data has multiple folders copy them all when copying.
> Fix: Remove caution export 2nd skin and better data handling

- python/vtool/process_manager/ui_view.py
- python/vtool/qt_ui.py
- python/vtool/util_file.py
* no slashes at start
* auto complete
* keep focus
> Fix: sub path filter

- python/vtool/data.py
- python/vtool/process_manager/ui_data.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/process_manager/ui_settings.py
> Improvement: data use thumbnails setting

- python/vtool/qt_ui.py
Hi! 
When testing Vetala in maya-2025, we found that Maya hanged when opening a Vetala script.
Investigation showed that `QRegularExpression.matchedLength` returned `-1`, resulting in an infinite `while` loop in `PythonHighlighter.match_multiline`.
However, `QRegularExpression.matchedLength` don't even exist in PySide6.
More investigation showed that  `QRegularExpression.matchedLength` is monkey patched by the Shotgun Toolkit!
https://github.com/shotgunsoftware/tk-core/blob/v0.23.0/python/tank/util/pyside6_patcher.py#L354-L359
And the patch is incomplete, here's the part where `matchedLength` return `-1`.
https://github.com/shotgunsoftware/tk-core/blob/v0.23.0/python/tank/util/pyside6_patcher.py#L397
```
>>> from PySide6.QtCore import QRegularExpression
>>> …
```
> Fix PythonHighlighter PySide6 compatibility
