louisVottero/vtool

- python/vtool/data.py
- python/vtool/version.txt
Importing onto skin cluster using setAttr instead of the maya API.  Nurbs generally don't have as many points to loop through as meshes, so they don't need the api speed boost.
When I have more time I will look again at getting it to work with the API for nurbs
> setting nurbs weights the old way

- python/vtool/process_manager/ui_data.py
```
if util.python_version < 3:
text = str(text)
else:
text = str(text, 'utf-8')
```
> Bug Fix - fix for code versions loading wrong in Python3

- python/vtool/util_file.py
util_file.get_ast_function_args() had a typo in a check in what should have been "python_version > 3", causing a failure when run in Python 2.7.
> fixed a typo in a check for Python 3

- python/vtool/maya_lib/deform.py
- python/vtool/version.txt
This removes the existing skin cluster on the nurbs surface if it exists before building the new one.
> Skin nurbs from mesh fix

- python/vtool/maya_lib/rigs.py
This fixes a bug with rigs.ControlRig where the control group was not being initialized properly anymore because of bad inheritance from the Rig class. 
This code
```
from vtool.maya_lib import rigs
rig = rigs.ControlRig('TEST_A', 'C')    
rig.create()
```
Would cause this error 
```
V:            Traceback (most recent call last):    
V:              File "D:\Programs/Vetala_test_0556\vtool\process_manager\process.py", line 2762, in run_script    
V:                result = module.main()    
V:              File "D:/Projects/work/ib_proj/mg2_test/_dev/python3_tests_vetala_055x/rig_controls_test_maya_2023/.code/rig_god/rig_god.py", line 6, in main    
V:                rig.create()    
V:              File "D:\Programs/Vetala_test_0556\vtool\maya_lib\rigs.py", line 362, in …
```
> Bug Fix: ControlRig controlVisibility error

- python/vtool/maya_lib/attr.py
- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/rigs.py
This adds a bunch of new options to the FK rig, where information from the joints can be used to guide the rig.
```
def use_hierarchy_to_inform_parenting(self,bool_value):
"""
This will activate using the hierarchy of the joints to inform control parenting.
"""
self._use_hier_parent = bool_value
def use_hierarchy_to_inform_color(self, bool_value):
"""
This will activate using the color of the joints to inform control colors.
"""
self._use_hier_color = bool_value
def use_hierarchy_to_inform_naming(self, bool_value):
"""
This will activate using the naming of the joints to inform control naming.
"""
self._use_hier_name = bool_value
def use_hierarchy_to_inform_size(self, bool_value):
"""
This will activate using the radius of the joints to inform control size.
"""
self._use_hier_size = …
```
> use hierarchy in FK rig to color, name and parent controls

- python/vtool/maya_lib/deform.py
Transfering joints from one mesh to another was not always working in Maya 2022 and above. This fix hopefully solves this.
Also 
deform.proximity_wrap added
> Improvement: transfer xforms should work better in Maya 2022-2023

- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_util.py
- python/vtool/run_script_manager.py
This code would create an ik setup where some setup joints were parented outside of the setup_group.
```import sys
sys.path.append('D:/dev/git/vtool/python')
from vtool.maya_lib import rigs
import maya.cmds as cmds
joints = cmds.ls(type = 'joint')
rig = rigs.IkAppendageRig('test')
rig.set_joints(joints[:3])
rig.set_pole_offset(0.5)
rig.set_stretch_type(1)
rig.create()```
> Fix: IkAppendageRig.set_stretchy_type(1) joint chain not parented under setup correctly.

- python/vtool/qt_ui.py
When clicking away from an object the edit state would remain open.
> Fix: script_manager edit state when clicking away

- python/vtool/maya_lib/rigs.py
- python/vtool/util_file.py
There is now a _pre_create function that runs before the create function on rig classes.
This was added to help check the state of rig classes before they create. 
Currently it is just checking that joints have been passed to rigs that inherit from JointRig.
> Improvment: _pre_create function added to rig classes

- python/vtool/maya_lib/rigs.py
this fixes an issue where the ground rig wouldn't build because of a new pre create function that checks if the rig has joints passed in.  Ground rig doesn't require joints to be passed in.
> Fix: ground rig with new pre check

- python/vtool/maya_lib/rigs.py
The aim constraints in the ribbon stretch on off were causing the joints to rotate weird when the length of the ribbon would go below initial length.  This is now improved by turning off aiming when the length goes below initial, which avoids the weird rotation
> Improvement: Ribbon stretch on off now turns of aim constrains when length goes below initial.

- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_process_manager.py
When running the process manager ui outside of Maya inside of pyside, the code will still run.
> Fix: fixes scripts not running outside Maya

- python/vtool/process_manager/batch.py
- python/vtool/util.py
- python/vtool/util_file.py
Batch mode was dependent on Vetala being in the python path.  It now automatically finds Vetala based on the location of the batch file, and adds it to the sys.path.
Also some logic for finding the right mayapy executable when in Maya 2022 and above. 
When process ends any key can now be pressed to close the terminal.  This avoids having a maya crash log started every time you close the terminal (might just be a windows 11 thing)
> Fix: batch mode, making it more stable

- python/vtool/maya_lib/geo.py
for convenience geo.get_meshes_in_list now returns the full path to the transform.
> Fix: geo.get_meshes_in_list returns full path

- python/vtool/process_manager/ui_data.py
The build save widget need to run self.set_directory with the new directory.
> Fix: build save widget getting out of sync

- python/vtool/maya_lib/rigs_util.py
fixes ik/fk matching no longer working because of a bool value that shouldn't have been there.
> Fix: controlVisibility getting mix up ik/fk match

- python/vtool/data.py
- python/vtool/process_manager/ui_data.py
When exporting multiple models variants and lods with potentially same named geo, it is better to always have long mesh names to avoid conflicts when not all variants and lods are present
> Added long name skin weight option, fixed data right click menu create

- python/vtool/maya_lib/__init__.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/process_manager/ui_settings.py
- python/vtool/qt_ui.py
First pass at main process ui simplification
This organizes the tabs a bit better.
Removes the Build Save from the bottom of the ui to save space. 
Data and Code behave like other tabs.  To have full space use the Full button at the top.
> Simplification: Process UI 

- python/vtool/maya_lib/geo.py
geo.transforms_to_polygon was leaving uv history on the mesh.  This was affecting uv pin constraints adversely
> Fix: geo.transforms_to_polygon uv history fix

- python/vtool/process_manager/ui_data.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/process_manager/ui_settings.py
The setting for the data sidebar visibility no longer requires a restart
Code Text Size now has a limit to reflect the limits of PySide QFont
> Fix:  Data Sidebar Setting and Code Text Size 

- python/vtool/maya_lib/rigs.py
This fixes the scapula flipping when the character is rotated 180 degrees upside down
It also add an improvement to the back leg to turn off the auto ankle, for more stable sitting poses
> Fix: Scapula upside down flip, Improvement: Auto ankle switch

- python/vtool/data.py
- python/vtool/maya_lib/deform.py
- python/vtool/process_manager/ui_data.py
This adds support for 2 skin clusters on one mesh.  
This can support 3 or more, if the user manually sets up 3 or more.   
Could update the ui for 3 or more support as requested.  In a way that its easy to export/import without having to manually setup.
> Added: Multi skincluster

- install/userSetup.py
- python/vtool/maya_lib/ui.py
- python/vtool/maya_lib/ui_core.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/process_manager/ui_settings.py
- python/vtool/util_file.py
I'm updating refactoring a little the functionality when loading vetala
The following code will be valid once the branch is merged
```
ui.tool_manager(directory = 'E:/temp/vetala_project/')
ui.tool_manager('Hub UI Name', directory = 'E:/temp/vetala_project/')
#these will have vetala settings load to the specific directory.  I think this will be useful for testing. Easier to keep your work separate from your test environment.
#the default has always been something like
#C:\Users\Louis Vottero\Documents\process_manager\project
#now this can be customized
window = ui.process_manager('E:/temp/vetala_project/')
#This launches the process manager with base directory for settings set to the path specified. This is pretty much the same as the lines above, except that you have a handle on the …
```
> Improvement: Settings directory and project history, dockable settings

- python/vtool/maya_lib/corrective.py
This would cause an error to happen if joints were locked or connected.  Now it just skips over if they are locked or connected.
> Fix: corrective set translate on joints error

- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/geo.py
* geo.transfer_uvs_from_mesh_to_group  becomes geo.transfer_uvs_from_combine_mesh_to_uncombine_group
* deform.skin_mesh_from_mesh now searches the current uvs instead of using map1
> Fix: "map1" passed instead of current uv map. 

- python/vtool/maya_lib/blendshape.py
Adding targets no longer checks topology, allowing shapes to be transfered from cutoff head to full body
> Fix: blendshape.transfer_blendshape_targets

- python/vtool/maya_lib/deform.py
This avoids a memory leak in linux and sometimes windows
> fix: turning undo off for deform.skin_mesh_from_mesh

- python/vtool/util_file.py
It seems the copy command in linux works like this
when copying first to second using cp in linux
first = /my/path/my_folder
second = /my/other_path/my_folder
the result in linux:  /my/other_path/my_folder/my_folder
the result in windows: /my/other_path/my_folder
however if 
first = /my/path/my_folder
second = /my/other_path/my_folder/version
the result in linux: /my/other_path/my_folder/version
the result in windows: /my/other_path/my_folder/version
in order to have linux work like windows, I check to see if the folder name being copied to is the same, and then copy to the parent folder instead if the names are the same.
> Fix: copying directories in linux

- python/vtool/maya_lib/deform.py
if keep_quads is set to zero it will use triangulated mesh, which sometimes gives more even topology across the surface at higher reduction percent.
> Improvement: TransferWeight.set_optimize_mesh now has keep_quads option

- python/vtool/maya_lib/core.py
- python/vtool/util.py
Small bugfix where a list was being returned like a callable and a fix to an intended tuple that was missing a comma.
> Tuple list bugfix 10 30 2023

- python/vtool/data.py
- python/vtool/maya_lib/api.py
- python/vtool/maya_lib/corrective.py
- python/vtool/maya_lib/deform.py
- python/vtool/maya_lib/geo.py
- python/vtool/maya_lib/rigs.py
- python/vtool/maya_lib/rigs_dev.py
- python/vtool/maya_lib/rigs_old.py
- python/vtool/maya_lib/rigs_util.py
- python/vtool/maya_lib/space.py
- python/vtool/maya_lib/ui_lib/ui_corrective.py
- python/vtool/maya_lib/ui_lib/ui_fx.py
- python/vtool/maya_lib/ui_lib/ui_picker.py
- python/vtool/process_manager/process.py
- python/vtool/process_manager/ui_code.py
- python/vtool/process_manager/ui_data.py
- python/vtool/process_manager/ui_options.py
- python/vtool/process_manager/ui_process_maintenance.py
- python/vtool/process_manager/ui_process_settings.py
- python/vtool/process_manager/ui_settings.py
- python/vtool/process_manager/ui_templates.py
- python/vtool/qt_ui.py
- python/vtool/ramen/rigs.py
- python/vtool/ramen/rigs_maya.py
- python/vtool/ramen/ui_lib/ui_nodes.py
- python/vtool/util.py
These changes have been made to address rogue object attributes being initialized in methods rather than on initialization. While this isn't particularly terrible, its best practice to go back and specify them in the init statement, as to inform the developer of whats being potentially mutated, stored, and worked on.
This also tends to assist developers when debugging.
> Instance attribute fixes 11 06 2023

- python/vtool/maya_lib/space.py
When freezing scale in orient joints the segment scale compensate would automatically get turned back on. This fixes that so segment scale compensate keeps the state it was in
> Fix: This fixes an issue with segment scale compensate and orient joint

- python/vtool/data.py
- python/vtool/process_manager/ui_data.py
- python/vtool/process_manager/ui_process_manager.py
- python/vtool/qt_ui.py
- python/vtool/util_file.py
This fixes some issues when switching projects
The data file widget gets it directory set to None when project is switched. These updates help handle some issues with setting the directory to None
> switching project fix, hide file widget when no directory

- python/vtool/maya_lib/rigs_util.py
This fixes the compression joint top locator not following properly
> Fix: rigs_util.create_compression_joint

- python/vtool/maya_lib/deform.py
Maya by default makes the skin cluster first when adding it to a deformation stack. Vetala was working like this but changed when multi skin cluster export was introduced.
> Fix: Multi skin clusters, made the front of chain flag for additional skin clusters

- python/vtool/maya_lib/geo.py
- python/vtool/maya_lib/ui_lib/ui_rig.py
This fixes create joints on curve to work on multiple selected curves
It also fixes snap joints to curve when setting an joint count larger than the current selection to work in hierarchy when creating new joints.
> Fix: Create curve and snap cuve

- python/vtool/ramen/ui_lib/ui_nodes.py
Windows - contextMenuEvent happens after mouse button release 
Linux - contextMenuEvent happens on mouse press. In Linux this ends up eating the right mouse release event. 
This code helps move the menu building to the mouse release event.
> Fix: Ramen Linux right click menu fix

- python/vtool/process_manager/ui_options.py
- python/vtool/util.py
When options are referenced and there's an error in the script (edit mode) reference options unload instead of leaving garbage behind.
> Fix: Referenced options

- python/vtool/maya_lib/space.py
This also fixes space orient_x_to_child, orient_y_to_child command (etc)
> Fix: orient joints now initializes children info better

- python/vtool/ramen/rigs_unreal.py
- python/vtool/unreal_lib/graph.py
- python/vtool/util.py
This fixes the adding animation channels erroring on creation in Unreal 5.4 because they changed the inputs needed.
> Fix: Unreal 54 wheel fix

- python/vtool/maya_lib/space.py
Just a small tweak, create_multi_follow now uses the names of the transform driving the follow in the title instead of the follower prefixed names.
> Improvement: space.create_mulit_follow title tweak

- python/vtool/maya_lib/core.py
- python/vtool/maya_lib/geo.py
* core.get_active_orig_node returns None if no origs instead of error 
* geo.unlock_normals properly deletes intermediate object history.
> Fix: unlock_normals bugs

- python/vtool/maya_lib/blendshape.py
when using create_target in the blendshape.Blendshape class the target would error if pruning was set but there was nothing to prune.
> Fix: blendshape.Blenshape.create_target error when nothing pruned.

- python/vtool/data.py
If skin weights exported non-unique name, import works on all matching meshes if model becomes non-unique
> Fix: Skin weight non unique

- python/vtool/maya_lib/blendshape.py
The targets in the target group were all being named the same. This fixes it so they get renamed to the target name stored in the blendshape
> Fix: blendshape recreate_all target names in group

- python/vtool/ramen/rigs_unreal.py
the wheel controls would stay even after the joints were disconnected.  This checks to see if there are any joints before spawning controls.
> Fix: Ramen Unreal Wheel Rig deals gracefully with no joints

- python/vtool/maya_lib/blendshape.py
If the source mesh was parented under world it would error.
> Fix: transfer_blendshape_targets when using wrap_mesh.

- python/vtool/process_manager/process.py
- python/vtool/qt_ui.py
When vetala loads a python file and runs it, its handling some of the sourcing itself.  This saves the user having to do imp.reload().
However in the previous release modules were reloading every time a script was run.
Now they reload on save.   
This brings the behavior back to how it was working before, with just the addition of reloading the module on save.
> Fix: move reload module to save instead of run, and only reload saved

- python/vtool/maya_lib/deform.py
There was a multiplication of the weights happening per vert that causes the source joints to not completely take over the destination joints if the destination joints didn't have a total weight that added to 1. 
Simply removing the line
`value = value * destination_value `
seems to be the fix
> Fix: deform.TransferWeight.transfer_joint_to_joint
